// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaonhudtcoxgbyqrhqex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhhb25odWR0Y294Z2J5cXJocWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNTcxNDgsImV4cCI6MjA1NTgzMzE0OH0.zLKpU6coXQCMfoS_4OS2jSKgOdEJl6QlGRQ57gBLlto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);